[tool.poetry]
name = "project-dependencies"
version = "0.1.0"
description = ""
authors = ["Anatolii.Dubovskyi <anatolii.dubovskyi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.10.0"
behave = "1.2.6"
requests = "^2.31.0"
webdriver-manager = "^3.8.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
